export { Home } from './Home';
export { Signup } from './Signup';
export { Login } from './Login';
export { RecruitmentNew } from './RecruitmentNew';
export { RecruitmentEdit } from './RecruitmentEdit';
export { Dashboard } from './Dashboard';
export { DashboardRecruitments } from './DashboardRecruitments';
export { DashboardStocks } from './DashboardStocks';
export { RecruitmentDetails } from './RecruitmentDetails';
